/* eslint-disable */
// Auto-generated by scripts/generate-learning-materials.mjs
// Do not edit manually.

export interface LearningMaterialGenerated {
  id: string;
  sequence: number;
  level: '入门' | '进阶';
  fileName: string;
  title: string;
  knowledgePointTitle: string;
  learningGoal: string;
  coreConcepts: string[];
  excerptBlocks: string[];
  practicePrompt: string;
  publicSearchKeywords: string[];
  prerequisites: string[];
  tags: string[];
}

export interface LearningMaterialsGeneratedPayload {
  generatedAt: string;
  sourceRoot: string;
  materials: LearningMaterialGenerated[];
}

export const learningMaterialsGenerated: LearningMaterialsGeneratedPayload = {
  "generatedAt": "2026-03-05T05:56:42.511Z",
  "sourceRoot": "works-docs/ming/ref/国学",
  "materials": [
    {
      "id": "lm_sanming",
      "sequence": 1,
      "level": "入门",
      "fileName": "八字 - 三命通会.txt",
      "title": "《三命通会》五行生克入门",
      "knowledgePointTitle": "理解五行生克与干支取象的基础逻辑",
      "learningGoal": "建立“先五行、后干支、再格局”的命理分析基础顺序。",
      "coreConcepts": [
        "五行生成",
        "相生相克",
        "日主视角",
        "全局取用"
      ],
      "excerptBlocks": [
        "天高寥廓，六气回旋以成四时；地厚幽深，五行化生以成万物。",
        "可谓无穷而莫测者也。圣人立法以推步者，盖不能逃其数。观",
        "其立数之因，亦皆出乎自然。故载于经典，同而不异，"
      ],
      "practicePrompt": "任选一个八字样例，先只写出五行分布和生克链条，再判断哪一环最失衡，并给出补偏建议。",
      "publicSearchKeywords": [
        "三命通会 原文",
        "三命通会 五行生克",
        "日主 月令 取用"
      ],
      "prerequisites": [],
      "tags": [
        "sizhu_bazi",
        "wuxing_energy"
      ]
    },
    {
      "id": "lm_yuanhai",
      "sequence": 2,
      "level": "入门",
      "fileName": "八字 - 渊海子平.txt",
      "title": "《渊海子平》十神与日主关系",
      "knowledgePointTitle": "按“日主中心”读懂十神关系",
      "learningGoal": "把十神关系从“背诵表”转成“关系推理”。",
      "coreConcepts": [
        "日主中心",
        "十神映射",
        "月令提纲",
        "岁运配合"
      ],
      "excerptBlocks": [
        "以甲为例★见甲：为比肩、兄弟。",
        "见乙：为劫财、败财，剋父及妻。",
        "见丙：为食神、天厨、寿星，为男。"
      ],
      "practicePrompt": "以甲日主和乙日主各举一例，写出它们看到同一干时为何十神定义不同，并说明实际影响。",
      "publicSearchKeywords": [
        "渊海子平 十神",
        "以日为主 月为提纲",
        "渊海子平 原文"
      ],
      "prerequisites": [
        "lm_sanming"
      ],
      "tags": [
        "sizhu_bazi",
        "wuxing_energy"
      ]
    },
    {
      "id": "lm_jiejie",
      "sequence": 3,
      "level": "入门",
      "fileName": "1900-2030年的交节时间1.csv",
      "title": "交节时间数据校验基础",
      "knowledgePointTitle": "用交节边界修正排盘时间误差",
      "learningGoal": "学会在节气临界日用数据校验“节前/节后”归属。",
      "coreConcepts": [
        "交节边界",
        "月令切换",
        "时间戳校验",
        "排盘对比"
      ],
      "excerptBlocks": [
        "样例节气时间：190001060209 / 190001201938 / 190002041357 / 190002191007 / 190003060827 / 190003210944 / 190004051358 / 190004202132 / 190005060801 / 190005212122",
        "可直接用于“出生时刻是否跨节气”校验，避免月令误判。"
      ],
      "practicePrompt": "选一个接近节气切换的出生时刻，用本地排盘与外部排盘对比“月令是否切换”，记录差异来源。",
      "publicSearchKeywords": [
        "交节时间 数据",
        "二十四节气 精确时刻",
        "节气边界 排盘"
      ],
      "prerequisites": [
        "lm_sanming"
      ],
      "tags": [
        "natural_object_ceremonies",
        "wuxing_energy",
        "sizhu_bazi"
      ]
    },
    {
      "id": "lm_yuding_liuren",
      "sequence": 4,
      "level": "进阶",
      "fileName": "御定六壬直指.txt",
      "title": "《御定六壬直指》六壬体系入门",
      "knowledgePointTitle": "建立六壬“起课-断课”的序列意识",
      "learningGoal": "理解六壬与四柱体系不同的推演路径，避免混用规则。",
      "coreConcepts": [
        "课体结构",
        "起课顺序",
        "时空应象",
        "断课框架"
      ],
      "excerptBlocks": [
        "该资料用于六壬学习扩展，建议与术语表配套，先术语后课式再断例。",
        "当前整理版以方法论导读为主，便于纳入学习路径而非直接背诵。"
      ],
      "practicePrompt": "围绕同一问题，分别写出“四柱分析步骤”和“六壬分析步骤”，对比两者输入与输出差异。",
      "publicSearchKeywords": [
        "御定六壬直指 原文",
        "大六壬 入门",
        "六壬 起课 断课"
      ],
      "prerequisites": [
        "lm_yuanhai"
      ],
      "tags": [
        "natural_object_ceremonies"
      ]
    },
    {
      "id": "lm_kuaisu_qipan",
      "sequence": 5,
      "level": "进阶",
      "fileName": "大六壬 - 快速起盘法.txt",
      "title": "大六壬快速起盘法",
      "knowledgePointTitle": "掌握“相对位置”快速起盘核心",
      "learningGoal": "把起盘速度训练为稳定可复现的流程动作。",
      "coreConcepts": [
        "相对位置",
        "地盘天盘",
        "月将占时",
        "四课三传"
      ],
      "excerptBlocks": [
        "大六壬 快速起盘训练方法",
        "我们来探讨不用纸、笔，不用掐掌诀，最多用二十秒内起好一个完整的大六壬课的方法。",
        "要在转眼间起好四课三传，配好天官（或称天将，即贵人），其核心诀窍实际只有四个字：相对位置！一个是月将与占时的相对位置，一个是天官之间的相对位置，熟练把握了这两点，起课的速度自然会突飞猛进。"
      ],
      "practicePrompt": "按文中步骤做 10 次“20 秒起盘”训练，记录每次错在哪里，并建立自己的纠错清单。",
      "publicSearchKeywords": [
        "大六壬 快速起盘法",
        "月将 占时 相对位置",
        "四课三传 训练"
      ],
      "prerequisites": [
        "lm_yuding_liuren"
      ],
      "tags": [
        "natural_object_ceremonies",
        "sizhu_bazi"
      ]
    }
  ]
} as const;
